// Phonics Worksheet Generator — word bank
// Each pattern: key, label (shown to teacher), grapheme (the letters), exampleWord,
// and a list of words, each with one example sentence (blank marked with ___).

const PATTERNS = {
  sh: { label: "sh (ship)", grapheme: "sh", exampleWord: "ship", words: [
    { word: "ship", sentence: "The ___ sailed across the sea." },
    { word: "shop", sentence: "We went to the ___ to buy milk." },
    { word: "fish", sentence: "I saw a ___ swim in the pond." },
    { word: "wish", sentence: "Close your eyes and make a ___." },
    { word: "shell", sentence: "I found a ___ on the beach." },
    { word: "shark", sentence: "A ___ has very sharp teeth." },
    { word: "brush", sentence: "I use a ___ to clean my hair." },
    { word: "flash", sentence: "I saw a ___ of lightning." },
  ]},
  ch: { label: "ch (chip)", grapheme: "ch", exampleWord: "chip", words: [
    { word: "chick", sentence: "The ___ is small and fluffy." },
    { word: "chin", sentence: "I hurt my ___ when I fell." },
    { word: "much", sentence: "How ___ milk do you want?" },
    { word: "lunch", sentence: "We ate ___ at school." },
    { word: "beach", sentence: "We went to the ___ to swim." },
    { word: "chess", sentence: "I like to play ___ with my dad." },
    { word: "peach", sentence: "I ate a juicy ___." },
    { word: "chest", sentence: "I put my toys in the ___." },
  ]},
  th: { label: "th (thin)", grapheme: "th", exampleWord: "thin", words: [
    { word: "this", sentence: "I like ___ book." },
    { word: "that", sentence: "Can I have ___ one?" },
    { word: "thin", sentence: "The paper is very ___." },
    { word: "bath", sentence: "I had a warm ___ before bed." },
    { word: "moth", sentence: "A ___ flew near the light." },
    { word: "tenth", sentence: "Today is the ___ of May." },
    { word: "thumb", sentence: "I hurt my ___." },
    { word: "cloth", sentence: "Wipe the table with a ___." },
  ]},
  ai: { label: "ai (rain)", grapheme: "ai", exampleWord: "rain", words: [
    { word: "rain", sentence: "The ___ fell all day." },
    { word: "train", sentence: "We rode on the ___ to the city." },
    { word: "snail", sentence: "We saw a ___ in the garden." },
    { word: "paint", sentence: "I like to ___ pictures." },
    { word: "chain", sentence: "The dog has a metal ___ on its collar." },
    { word: "sail", sentence: "We will ___ across the lake." },
    { word: "mail", sentence: "I put a letter in the ___." },
    { word: "tail", sentence: "The dog wagged its ___." },
  ]},
  ay: { label: "ay (play)", grapheme: "ay", exampleWord: "play", words: [
    { word: "play", sentence: "I like to ___ in the park." },
    { word: "day", sentence: "Today is a sunny ___." },
    { word: "tray", sentence: "Mum carried the cups on a ___." },
    { word: "stay", sentence: "Please ___ here with me." },
    { word: "spray", sentence: "We used water ___ to cool down." },
    { word: "gray", sentence: "The sky turned ___ before the storm." },
    { word: "clay", sentence: "I made a pot from ___." },
    { word: "hay", sentence: "The horse ate some ___." },
  ]},
  ee: { label: "ee (tree)", grapheme: "ee", exampleWord: "tree", words: [
    { word: "tree", sentence: "I sat under a tall ___." },
    { word: "feet", sentence: "My ___ feel cold." },
    { word: "green", sentence: "The frog is ___." },
    { word: "sleep", sentence: "I go to ___ at night." },
    { word: "sweet", sentence: "The cake tastes ___." },
    { word: "queen", sentence: "The ___ wore a golden crown." },
    { word: "sheep", sentence: "The ___ ate grass in the field." },
    { word: "bee", sentence: "I saw a ___ fly past." },
  ]},
  ea: { label: "ea (leaf)", grapheme: "ea", exampleWord: "leaf", words: [
    { word: "leaf", sentence: "The ___ fell from the tree." },
    { word: "bead", sentence: "She wore a ___ necklace." },
    { word: "seat", sentence: "Please take a ___." },
    { word: "beach", sentence: "We built a sandcastle at the ___." },
    { word: "dream", sentence: "I had a nice ___ about flying." },
    { word: "clean", sentence: "I helped ___ my room." },
    { word: "meal", sentence: "We ate a big ___." },
    { word: "peas", sentence: "I do not like ___." },
  ]},
  oa: { label: "oa (boat)", grapheme: "oa", exampleWord: "boat", words: [
    { word: "boat", sentence: "We sailed the ___ on the lake." },
    { word: "coat", sentence: "Put on your ___, it is cold." },
    { word: "soap", sentence: "Wash your hands with ___." },
    { word: "toast", sentence: "I had ___ for breakfast." },
    { word: "road", sentence: "We walked down the ___." },
    { word: "goat", sentence: "The ___ ate the grass." },
    { word: "float", sentence: "Wood can ___ on water." },
    { word: "coach", sentence: "The ___ trained our team." },
  ]},
  ow_snow: { label: "ow (snow)", grapheme: "ow", exampleWord: "snow", words: [
    { word: "snow", sentence: "It began to ___ outside." },
    { word: "grow", sentence: "Plants ___ in the sun." },
    { word: "blow", sentence: "The wind will ___ the leaves." },
    { word: "show", sentence: "I will ___ you my new toy." },
    { word: "glow", sentence: "The stars ___ at night." },
    { word: "throw", sentence: "I can ___ the ball far." },
    { word: "arrow", sentence: "The ___ hit the target." },
    { word: "window", sentence: "I looked out the ___." },
  ]},
  igh: { label: "igh (light)", grapheme: "igh", exampleWord: "light", words: [
    { word: "light", sentence: "Turn on the ___." },
    { word: "night", sentence: "Owls come out at ___." },
    { word: "right", sentence: "Turn ___ at the corner." },
    { word: "bright", sentence: "The sun was very ___." },
    { word: "fright", sentence: "The loud noise gave me a ___." },
    { word: "sight", sentence: "It was a beautiful ___." },
    { word: "tight", sentence: "My shoes feel too ___." },
    { word: "flight", sentence: "We took a long ___ on the plane." },
  ]},
  y_cry: { label: "y (cry)", grapheme: "y", exampleWord: "cry", words: [
    { word: "cry", sentence: "The baby began to ___." },
    { word: "dry", sentence: "Hang the towel up to ___." },
    { word: "fly", sentence: "Birds can ___ high in the sky." },
    { word: "sky", sentence: "The stars are in the ___." },
    { word: "try", sentence: "I will ___ my best." },
    { word: "shy", sentence: "The new boy is very ___." },
    { word: "spy", sentence: "I like to play I ___." },
    { word: "why", sentence: "___ are you sad?" },
  ]},
  ew: { label: "ew (grew)", grapheme: "ew", exampleWord: "grew", words: [
    { word: "grew", sentence: "The plant ___ very tall." },
    { word: "chew", sentence: "Please ___ your food well." },
    { word: "threw", sentence: "I ___ the ball to my friend." },
    { word: "drew", sentence: "She ___ a picture of a cat." },
    { word: "blew", sentence: "The wind ___ my hat away." },
    { word: "flew", sentence: "The bird ___ over the fence." },
    { word: "crew", sentence: "The ship's ___ worked hard." },
    { word: "screw", sentence: "I used a ___ to fix the shelf." },
  ]},
  ue: { label: "ue (glue)", grapheme: "ue", exampleWord: "glue", words: [
    { word: "blue", sentence: "The sky is ___ today." },
    { word: "glue", sentence: "I need some ___ to fix this." },
    { word: "true", sentence: "It is ___ that cats can climb trees." },
    { word: "clue", sentence: "The detective looked for a ___." },
    { word: "argue", sentence: "Please do not ___ with your sister." },
    { word: "rescue", sentence: "Firefighters ___ people from danger." },
    { word: "statue", sentence: "We saw a ___ in the park." },
    { word: "value", sentence: "This old coin has great ___." },
  ]},
  a_e: { label: "a_e (cake)", grapheme: "a_e", exampleWord: "cake", words: [
    { word: "cake", sentence: "We baked a ___ for the party." },
    { word: "gate", sentence: "Close the ___ behind you." },
    { word: "plane", sentence: "We flew on a ___." },
    { word: "snake", sentence: "The ___ hid under a rock." },
    { word: "plate", sentence: "I put food on my ___." },
    { word: "shake", sentence: "Please ___ the bottle before you open it." },
    { word: "grape", sentence: "I ate a purple ___." },
    { word: "whale", sentence: "The ___ swam in the deep sea." },
  ]},
  e_e: { label: "e_e (these)", grapheme: "e_e", exampleWord: "these", words: [
    { word: "these", sentence: "I like ___ shoes." },
    { word: "theme", sentence: "Our party has a space ___." },
    { word: "complete", sentence: "Please ___ your homework." },
    { word: "delete", sentence: "Click here to ___ the file." },
    { word: "extreme", sentence: "It was an ___ sport." },
    { word: "compete", sentence: "The two teams will ___ today." },
    { word: "athlete", sentence: "The ___ ran very fast." },
    { word: "scene", sentence: "We watched a funny ___ in the movie." },
  ]},
  i_e: { label: "i_e (kite)", grapheme: "i_e", exampleWord: "kite", words: [
    { word: "kite", sentence: "I flew my ___ in the park." },
    { word: "bike", sentence: "I ride my ___ to school." },
    { word: "smile", sentence: "She gave a big ___." },
    { word: "slide", sentence: "We went down the ___." },
    { word: "time", sentence: "What ___ is it?" },
    { word: "five", sentence: "I have ___ fingers on each hand." },
    { word: "shine", sentence: "The sun will ___ today." },
    { word: "prize", sentence: "She won a ___ at the fair." },
  ]},
  o_e: { label: "o_e (bone)", grapheme: "o_e", exampleWord: "bone", words: [
    { word: "bone", sentence: "The dog buried its ___." },
    { word: "rope", sentence: "We tied the boat with a ___." },
    { word: "stone", sentence: "I found a ___ by the river." },
    { word: "smoke", sentence: "The fire made grey ___." },
    { word: "close", sentence: "Please ___ the door." },
    { word: "phone", sentence: "I called my mum on the ___." },
    { word: "globe", sentence: "We spun the ___ to find a country." },
    { word: "note", sentence: "I wrote a ___ to my friend." },
  ]},
  u_e: { label: "u_e (cube)", grapheme: "u_e", exampleWord: "cube", words: [
    { word: "cube", sentence: "The ice made a ___ shape." },
    { word: "cute", sentence: "The puppy is very ___." },
    { word: "tube", sentence: "I squeezed the paint ___." },
    { word: "flute", sentence: "She plays the ___ in music class." },
    { word: "June", sentence: "My birthday is in ___." },
    { word: "rule", sentence: "We must follow this ___." },
    { word: "mule", sentence: "A ___ looks like a small horse." },
    { word: "huge", sentence: "The elephant is a ___ animal." },
  ]},
  oi: { label: "oi (coin)", grapheme: "oi", exampleWord: "coin", words: [
    { word: "coin", sentence: "I found a shiny ___." },
    { word: "soil", sentence: "Plants grow in the ___." },
    { word: "boil", sentence: "We will ___ the eggs." },
    { word: "point", sentence: "Please ___ to the map." },
    { word: "voice", sentence: "She has a loud ___." },
    { word: "join", sentence: "Can I ___ the game?" },
    { word: "spoil", sentence: "Do not ___ your dinner." },
    { word: "noise", sentence: "That was a loud ___." },
  ]},
  oy: { label: "oy (toy)", grapheme: "oy", exampleWord: "toy", words: [
    { word: "toy", sentence: "I got a new ___." },
    { word: "boy", sentence: "The ___ kicked the ball." },
    { word: "joy", sentence: "The puppy brings us ___." },
    { word: "enjoy", sentence: "I ___ playing outside." },
    { word: "royal", sentence: "The king wore a ___ crown." },
    { word: "annoy", sentence: "Please do not ___ your sister." },
    { word: "employ", sentence: "The shop will ___ more workers." },
    { word: "destroy", sentence: "Fire can ___ a forest." },
  ]},
  ar: { label: "ar (star)", grapheme: "ar", exampleWord: "star", words: [
    { word: "star", sentence: "I can see a ___ in the sky." },
    { word: "car", sentence: "We drove in the ___." },
    { word: "park", sentence: "We played at the ___." },
    { word: "farm", sentence: "Cows live on the ___." },
    { word: "shark", sentence: "A ___ swims in the sea." },
    { word: "dark", sentence: "It is very ___ at night." },
    { word: "cart", sentence: "We pushed the shopping ___." },
    { word: "sharp", sentence: "The knife is very ___." },
  ]},
  or: { label: "or (fork)", grapheme: "or", exampleWord: "fork", words: [
    { word: "fork", sentence: "I eat with a ___." },
    { word: "corn", sentence: "We grew yellow ___ on the farm." },
    { word: "storm", sentence: "The ___ knocked down a tree." },
    { word: "horse", sentence: "I rode a ___." },
    { word: "short", sentence: "My hair is very ___." },
    { word: "sport", sentence: "My favourite ___ is football." },
    { word: "snort", sentence: "The pig gave a loud ___." },
    { word: "torch", sentence: "We used a ___ to see in the dark." },
  ]},
  ow_cow: { label: "ow (cow)", grapheme: "ow", exampleWord: "cow", words: [
    { word: "cow", sentence: "The ___ eats grass in the field." },
    { word: "how", sentence: "___ did you do that?" },
    { word: "now", sentence: "Please come here right ___." },
    { word: "town", sentence: "We drove into ___." },
    { word: "brown", sentence: "My dog has ___ fur." },
    { word: "crown", sentence: "The king wore a golden ___." },
    { word: "clown", sentence: "The ___ made us laugh." },
    { word: "owl", sentence: "An ___ hooted in the night." },
  ]},
  ou: { label: "ou (cloud)", grapheme: "ou", exampleWord: "cloud", words: [
    { word: "cloud", sentence: "I saw a fluffy ___." },
    { word: "mouth", sentence: "Open your ___ wide." },
    { word: "sound", sentence: "I heard a strange ___." },
    { word: "round", sentence: "The wheel is ___." },
    { word: "house", sentence: "We live in a small ___." },
    { word: "mouse", sentence: "A little ___ ran past." },
    { word: "count", sentence: "Please ___ to ten." },
    { word: "out", sentence: "Let's go ___ to play." },
  ]},
  air: { label: "air (chair)", grapheme: "air", exampleWord: "chair", words: [
    { word: "hair", sentence: "She brushed her ___." },
    { word: "chair", sentence: "Please sit on the ___." },
    { word: "fair", sentence: "We went to the school ___." },
    { word: "stair", sentence: "I walked up the ___." },
    { word: "pair", sentence: "I have a new ___ of shoes." },
    { word: "repair", sentence: "Dad will ___ my bike." },
    { word: "airport", sentence: "We flew from the ___." },
    { word: "fairy", sentence: "The ___ waved her wand." },
  ]},
  ear: { label: "ear (hear)", grapheme: "ear", exampleWord: "hear", words: [
    { word: "hear", sentence: "I can ___ the birds sing." },
    { word: "near", sentence: "My school is ___ my house." },
    { word: "year", sentence: "We are one ___ older today." },
    { word: "dear", sentence: "My ___ friend, thank you." },
    { word: "clear", sentence: "The water in the pool is ___." },
    { word: "spear", sentence: "The hunter held a sharp ___." },
    { word: "fear", sentence: "I have no ___ of the dark." },
    { word: "tear", sentence: "A ___ ran down her cheek." },
  ]},

  // ===================================================================
  // Foundation — single letter graphemes (m,s,t,a,p,i,f,r,o,c,d,h,e,n,g,l,
  // k,u,b,j,w,v,x,y,z — every letter except q, which is only taught as "qu")
  // ===================================================================
  m: { label: "m (mat)", grapheme: "m", exampleWord: "mat", words: [
    { word: "mat", sentence: "Wipe your feet on the ___." },
    { word: "man", sentence: "The ___ waved to us." },
    { word: "mud", sentence: "The pig rolled in the ___." },
    { word: "map", sentence: "We used a ___ to find the way." },
    { word: "mum", sentence: "My ___ is very kind." },
    { word: "milk", sentence: "I drink ___ every morning." },
    { word: "mask", sentence: "I made a paper ___." },
    { word: "mix", sentence: "Please ___ the paint colours." },
  ]},
  s: { label: "s (sun)", grapheme: "s", exampleWord: "sun", words: [
    { word: "sun", sentence: "The ___ is bright today." },
    { word: "sit", sentence: "Please ___ down." },
    { word: "sock", sentence: "I lost one ___." },
    { word: "sad", sentence: "The film made me feel ___." },
    { word: "sand", sentence: "We built a castle in the ___." },
    { word: "soft", sentence: "The blanket is very ___." },
    { word: "sip", sentence: "I took a ___ of water." },
    { word: "sell", sentence: "We will ___ cakes at the fete." },
  ]},
  t: { label: "t (top)", grapheme: "t", exampleWord: "top", words: [
    { word: "top", sentence: "Put the lid on ___." },
    { word: "ten", sentence: "I can count to ___." },
    { word: "tap", sentence: "Turn off the ___." },
    { word: "tin", sentence: "The beans are in a ___." },
    { word: "tent", sentence: "We slept in a ___." },
    { word: "test", sentence: "I studied for my spelling ___." },
    { word: "tub", sentence: "I filled the ___ with water." },
    { word: "tell", sentence: "Can you ___ me a story?" },
  ]},
  a: { label: "a (cat)", grapheme: "a", exampleWord: "cat", words: [
    { word: "cat", sentence: "The ___ is asleep on the mat." },
    { word: "hat", sentence: "I wear a ___ in the sun." },
    { word: "bag", sentence: "I packed my ___ for school." },
    { word: "man", sentence: "The ___ crossed the road." },
    { word: "ant", sentence: "An ___ crawled up the wall." },
    { word: "ask", sentence: "You can ___ me a question." },
    { word: "add", sentence: "Please ___ two more blocks." },
    { word: "apple", sentence: "I ate a red ___." },
  ]},
  p: { label: "p (pen)", grapheme: "p", exampleWord: "pen", words: [
    { word: "pen", sentence: "I wrote with a blue ___." },
    { word: "pig", sentence: "The ___ lives on the farm." },
    { word: "pot", sentence: "Mum put the soup in a ___." },
    { word: "pan", sentence: "We fried the eggs in a ___." },
    { word: "pop", sentence: "I heard the balloon ___." },
    { word: "park", sentence: "We played at the ___." },
    { word: "pin", sentence: "Be careful of the sharp ___." },
    { word: "pat", sentence: "I gave the dog a gentle ___." },
  ]},
  i: { label: "i (sit)", grapheme: "i", exampleWord: "sit", words: [
    { word: "sit", sentence: "Please ___ on the chair." },
    { word: "big", sentence: "The elephant is very ___." },
    { word: "six", sentence: "I am ___ years old." },
    { word: "pin", sentence: "I found a ___ on the floor." },
    { word: "ink", sentence: "The pen ran out of ___." },
    { word: "itch", sentence: "My arm has an ___." },
    { word: "insect", sentence: "A bee is a small ___." },
    { word: "inch", sentence: "The bug was one ___ long." },
  ]},
  o: { label: "o (hot)", grapheme: "o", exampleWord: "hot", words: [
    { word: "hot", sentence: "The soup is very ___." },
    { word: "top", sentence: "The bird sat on ___ of the tree." },
    { word: "dog", sentence: "My ___ likes to run." },
    { word: "box", sentence: "I put my toys in a ___." },
    { word: "on", sentence: "Please turn the light ___." },
    { word: "off", sentence: "Turn the tap ___." },
    { word: "odd", sentence: "Three is an ___ number." },
    { word: "ox", sentence: "The ___ pulled the cart." },
  ]},
  c: { label: "c (cat)", grapheme: "c", exampleWord: "cat", words: [
    { word: "cat", sentence: "The ___ chased the ball of wool." },
    { word: "cup", sentence: "I drank from a ___." },
    { word: "cap", sentence: "He wore a red ___." },
    { word: "cot", sentence: "The baby sleeps in a ___." },
    { word: "cub", sentence: "The lion ___ played with its mother." },
    { word: "camp", sentence: "We went to ___ over summer." },
    { word: "cast", sentence: "The doctor put a ___ on my arm." },
    { word: "cost", sentence: "How much does that ___?" },
  ]},
  d: { label: "d (dog)", grapheme: "d", exampleWord: "dog", words: [
    { word: "dog", sentence: "The ___ barked at the mail." },
    { word: "dad", sentence: "My ___ cooked dinner tonight." },
    { word: "dig", sentence: "We used a spade to ___." },
    { word: "den", sentence: "We built a ___ in the yard." },
    { word: "dot", sentence: "There is a ___ on the map." },
    { word: "desk", sentence: "I keep my books on my ___." },
    { word: "drum", sentence: "He plays the ___ in a band." },
    { word: "duck", sentence: "The ___ swam across the pond." },
  ]},
  h: { label: "h (hat)", grapheme: "h", exampleWord: "hat", words: [
    { word: "hat", sentence: "She wore a straw ___." },
    { word: "hen", sentence: "The ___ laid an egg." },
    { word: "hot", sentence: "It is very ___ today." },
    { word: "hop", sentence: "Rabbits ___ across the grass." },
    { word: "hut", sentence: "We stayed in a small ___." },
    { word: "hand", sentence: "Please raise your ___." },
    { word: "hill", sentence: "We rolled down the ___." },
    { word: "hint", sentence: "Can you give me a ___?" },
  ]},
  e: { label: "e (pen)", grapheme: "e", exampleWord: "pen", words: [
    { word: "pen", sentence: "I lost my favourite ___." },
    { word: "ten", sentence: "There are ___ apples in the bowl." },
    { word: "bed", sentence: "I made my ___ this morning." },
    { word: "leg", sentence: "I hurt my ___ playing football." },
    { word: "wet", sentence: "My shoes are ___ from the rain." },
    { word: "elf", sentence: "The ___ helped Santa wrap gifts." },
    { word: "end", sentence: "We reached the ___ of the road." },
    { word: "egg", sentence: "I had an ___ for breakfast." },
  ]},
  n: { label: "n (net)", grapheme: "n", exampleWord: "net", words: [
    { word: "net", sentence: "We caught the fish in a ___." },
    { word: "nap", sentence: "The baby had a short ___." },
    { word: "nut", sentence: "The squirrel buried a ___." },
    { word: "nod", sentence: "She gave a small ___." },
    { word: "neck", sentence: "The giraffe has a long ___." },
    { word: "nest", sentence: "The bird built a ___ in the tree." },
    { word: "north", sentence: "We travelled ___ for the holidays." },
    { word: "noise", sentence: "I heard a loud ___." },
  ]},
  g: { label: "g (get)", grapheme: "g", exampleWord: "get", words: [
    { word: "get", sentence: "Can you ___ the ball for me?" },
    { word: "gap", sentence: "There is a ___ in the fence." },
    { word: "gum", sentence: "She chewed a piece of ___." },
    { word: "dog", sentence: "My ___ likes to fetch sticks." },
    { word: "big", sentence: "We saw a ___ truck." },
    { word: "gift", sentence: "I gave her a ___ for her birthday." },
    { word: "grab", sentence: "Please ___ my hand." },
    { word: "gold", sentence: "The trophy was made of ___." },
  ]},
  l: { label: "l (leg)", grapheme: "l", exampleWord: "leg", words: [
    { word: "leg", sentence: "I hurt my ___ at the park." },
    { word: "log", sentence: "We sat on a ___ by the fire." },
    { word: "lid", sentence: "Please put the ___ on the box." },
    { word: "lip", sentence: "She bit her ___." },
    { word: "lamp", sentence: "Turn on the ___, it's dark." },
    { word: "list", sentence: "Mum wrote a shopping ___." },
    { word: "lock", sentence: "Remember to ___ the door." },
    { word: "lap", sentence: "The cat sat on my ___." },
  ]},
  k: { label: "k (kid)", grapheme: "k", exampleWord: "kid", words: [
    { word: "kid", sentence: "Every ___ in the class laughed." },
    { word: "kit", sentence: "I fixed my bike with a repair ___." },
    { word: "king", sentence: "The ___ wore a golden crown." },
    { word: "key", sentence: "I lost my house ___." },
    { word: "kick", sentence: "He gave the ball a big ___." },
    { word: "kettle", sentence: "Mum boiled water in the ___." },
    { word: "kangaroo", sentence: "A ___ hopped across the field." },
    { word: "koala", sentence: "The ___ slept in the tree." },
  ]},
  u: { label: "u (cup)", grapheme: "u", exampleWord: "cup", words: [
    { word: "cup", sentence: "I filled my ___ with juice." },
    { word: "sun", sentence: "The ___ is shining today." },
    { word: "bug", sentence: "A tiny ___ crawled on the leaf." },
    { word: "rug", sentence: "The cat slept on the ___." },
    { word: "mud", sentence: "My boots are covered in ___." },
    { word: "up", sentence: "Please stand ___." },
    { word: "us", sentence: "Come and play with ___." },
    { word: "under", sentence: "The ball rolled ___ the table." },
  ]},
  b: { label: "b (bag)", grapheme: "b", exampleWord: "bag", words: [
    { word: "bag", sentence: "I packed my school ___." },
    { word: "bed", sentence: "It is time to go to ___." },
    { word: "big", sentence: "That is a ___ dog." },
    { word: "bus", sentence: "We rode the ___ to school." },
    { word: "box", sentence: "The toys are in a ___." },
    { word: "bell", sentence: "I heard the school ___ ring." },
    { word: "brush", sentence: "I use a ___ to clean my teeth." },
    { word: "bath", sentence: "I had a warm ___ before bed." },
  ]},
  j: { label: "j (jam)", grapheme: "j", exampleWord: "jam", words: [
    { word: "jam", sentence: "I spread ___ on my toast." },
    { word: "jet", sentence: "The ___ flew high in the sky." },
    { word: "jog", sentence: "We went for a ___ this morning." },
    { word: "jug", sentence: "Fill the ___ with water." },
    { word: "jump", sentence: "Watch me ___ over the puddle." },
    { word: "jelly", sentence: "We had ___ for dessert." },
    { word: "jacket", sentence: "Put on your ___, it's cold." },
    { word: "job", sentence: "Feeding the fish is my ___." },
  ]},
  w: { label: "w (wet)", grapheme: "w", exampleWord: "wet", words: [
    { word: "wet", sentence: "My hair is still ___." },
    { word: "win", sentence: "I hope our team will ___." },
    { word: "wig", sentence: "The actor wore a funny ___." },
    { word: "web", sentence: "The spider spun a ___." },
    { word: "wag", sentence: "The dog began to ___ its tail." },
    { word: "wind", sentence: "The ___ blew the leaves away." },
    { word: "wish", sentence: "I made a ___ before I blew out the candles." },
    { word: "wall", sentence: "We painted the ___ blue." },
  ]},
  v: { label: "v (van)", grapheme: "v", exampleWord: "van", words: [
    { word: "van", sentence: "Dad drove the delivery ___." },
    { word: "vet", sentence: "We took our dog to the ___." },
    { word: "visit", sentence: "We will ___ Grandma today." },
    { word: "seven", sentence: "I have ___ marbles." },
    { word: "oven", sentence: "The cake is baking in the ___." },
    { word: "vase", sentence: "She put flowers in a ___." },
    { word: "vote", sentence: "We will ___ for our class captain." },
    { word: "cave", sentence: "The bear slept in a dark ___." },
  ]},
  x: { label: "x (box)", grapheme: "x", exampleWord: "box", words: [
    { word: "box", sentence: "I packed my toys in a ___." },
    { word: "fox", sentence: "A ___ ran across the field." },
    { word: "six", sentence: "I have ___ pencils." },
    { word: "mix", sentence: "Please ___ the batter well." },
    { word: "wax", sentence: "The candle is made of ___." },
    { word: "taxi", sentence: "We caught a ___ to the airport." },
    { word: "exit", sentence: "Please use the nearest ___." },
    { word: "fix", sentence: "Dad will ___ my bike." },
  ]},
  y_yes: { label: "y (yes)", grapheme: "y", exampleWord: "yes", words: [
    { word: "yes", sentence: "I said ___ to the party." },
    { word: "yak", sentence: "A ___ has long shaggy fur." },
    { word: "yellow", sentence: "The sun looks ___ in the sky." },
    { word: "yarn", sentence: "She knitted a scarf with blue ___." },
    { word: "yawn", sentence: "I gave a big ___ before bed." },
    { word: "yell", sentence: "Please do not ___ inside." },
    { word: "yogurt", sentence: "I had ___ with berries for lunch." },
    { word: "young", sentence: "The puppy is still very ___." },
  ]},
  z: { label: "z (zip)", grapheme: "z", exampleWord: "zip", words: [
    { word: "zip", sentence: "Please ___ up your jacket." },
    { word: "zoo", sentence: "We saw lions at the ___." },
    { word: "zebra", sentence: "A ___ has black and white stripes." },
    { word: "zero", sentence: "The score was ___ to ten." },
    { word: "buzz", sentence: "I heard the bee ___ past." },
    { word: "zigzag", sentence: "The path went in a ___." },
    { word: "zone", sentence: "This is a quiet reading ___." },
    { word: "zoom", sentence: "The car began to ___ down the road." },
  ]},

  // ===================================================================
  // Foundation — remaining consonant digraphs, doubled letters, qu
  // ===================================================================
  ck: { label: "ck (duck)", grapheme: "ck", exampleWord: "duck", words: [
    { word: "duck", sentence: "The ___ swam across the pond." },
    { word: "sock", sentence: "I found one missing ___." },
    { word: "rock", sentence: "We climbed onto a big ___." },
    { word: "kick", sentence: "He gave the ball a ___." },
    { word: "black", sentence: "My cat has ___ fur." },
    { word: "clock", sentence: "The ___ on the wall is loud." },
    { word: "truck", sentence: "The ___ carried the bricks." },
    { word: "sick", sentence: "I stayed home because I felt ___." },
  ]},
  ll: { label: "ll (bell)", grapheme: "ll", exampleWord: "bell", words: [
    { word: "bell", sentence: "I heard the school ___ ring." },
    { word: "doll", sentence: "She plays with her favourite ___." },
    { word: "ball", sentence: "We kicked the ___ in the yard." },
    { word: "well", sentence: "I hope you feel ___ soon." },
    { word: "shell", sentence: "I found a ___ on the beach." },
    { word: "spell", sentence: "Can you ___ your name?" },
    { word: "smell", sentence: "The flowers ___ lovely." },
    { word: "hill", sentence: "We rolled down the grassy ___." },
  ]},
  ff: { label: "ff (cliff)", grapheme: "ff", exampleWord: "cliff", words: [
    { word: "cliff", sentence: "We stood at the top of the ___." },
    { word: "puff", sentence: "I was out of ___ after the race." },
    { word: "sniff", sentence: "The dog began to ___ the ground." },
    { word: "stuff", sentence: "Please put your ___ away." },
    { word: "fluff", sentence: "The teddy bear is full of ___." },
    { word: "huff", sentence: "The wolf gave a big ___." },
    { word: "cuff", sentence: "My sleeve has a torn ___." },
    { word: "off", sentence: "Please turn the light ___." },
  ]},
  ss: { label: "ss (kiss)", grapheme: "ss", exampleWord: "kiss", words: [
    { word: "kiss", sentence: "Mum gave me a ___ goodnight." },
    { word: "miss", sentence: "I will ___ my friends over the holidays." },
    { word: "grass", sentence: "The dog ran across the ___." },
    { word: "dress", sentence: "She wore a pretty ___." },
    { word: "glass", sentence: "I drank water from a ___." },
    { word: "cross", sentence: "Look both ways before you ___ the road." },
    { word: "press", sentence: "Please ___ the button." },
    { word: "mess", sentence: "I made a ___ in the kitchen." },
  ]},
  zz: { label: "zz (buzz)", grapheme: "zz", exampleWord: "buzz", words: [
    { word: "buzz", sentence: "I heard the bee ___ past." },
    { word: "fizz", sentence: "The soda began to ___." },
    { word: "jazz", sentence: "We listened to ___ music." },
    { word: "fuzz", sentence: "The peach was covered in soft ___." },
    { word: "dizzy", sentence: "Spinning around made me feel ___." },
    { word: "puzzle", sentence: "We finished the jigsaw ___." },
    { word: "blizzard", sentence: "The ___ covered the town in snow." },
    { word: "drizzle", sentence: "A light ___ fell all morning." },
  ]},
  qu: { label: "qu (queen)", grapheme: "qu", exampleWord: "queen", words: [
    { word: "queen", sentence: "The ___ waved to the crowd." },
    { word: "quick", sentence: "The fox was very ___." },
    { word: "quiz", sentence: "We had a spelling ___ today." },
    { word: "quilt", sentence: "I stayed warm under my ___." },
    { word: "quiet", sentence: "Please be ___ in the library." },
    { word: "squid", sentence: "We saw a ___ at the aquarium." },
    { word: "quack", sentence: "The duck went ___." },
    { word: "question", sentence: "I have a ___ to ask." },
  ]},
  wh: { label: "wh (whale)", grapheme: "wh", exampleWord: "whale", words: [
    { word: "whale", sentence: "We saw a ___ swim past the boat." },
    { word: "wheel", sentence: "The car has a flat ___." },
    { word: "white", sentence: "Snow is bright ___." },
    { word: "wheat", sentence: "Bread is made from ___." },
    { word: "whisk", sentence: "Use a ___ to beat the eggs." },
    { word: "whistle", sentence: "The referee blew the ___." },
    { word: "what", sentence: "___ is your favourite colour?" },
    { word: "when", sentence: "___ is your birthday?" },
  ]},
  oo_moon: { label: "oo (moon)", grapheme: "oo", exampleWord: "moon", words: [
    { word: "moon", sentence: "I can see the ___ tonight." },
    { word: "spoon", sentence: "I ate my soup with a ___." },
    { word: "food", sentence: "The dog waited for its ___." },
    { word: "room", sentence: "Please tidy your ___." },
    { word: "zoo", sentence: "We saw lions at the ___." },
    { word: "boot", sentence: "I lost one ___ in the mud." },
    { word: "school", sentence: "I walk to ___ every day." },
    { word: "pool", sentence: "We swam in the ___." },
  ]},
  oo_book: { label: "oo (book)", grapheme: "oo", exampleWord: "book", words: [
    { word: "book", sentence: "I am reading a great ___." },
    { word: "look", sentence: "Come and ___ at this!" },
    { word: "foot", sentence: "I hurt my ___ playing football." },
    { word: "wood", sentence: "The table is made of ___." },
    { word: "good", sentence: "You did a ___ job." },
    { word: "hook", sentence: "Hang your coat on the ___." },
    { word: "cook", sentence: "I like to ___ with my dad." },
    { word: "wool", sentence: "The jumper is made of ___." },
  ]},
  ng: { label: "ng (ring)", grapheme: "ng", exampleWord: "ring", words: [
    { word: "ring", sentence: "The phone began to ___." },
    { word: "king", sentence: "The ___ lived in a castle." },
    { word: "song", sentence: "We sang a happy ___." },
    { word: "long", sentence: "The snake was very ___." },
    { word: "sing", sentence: "I love to ___ in the choir." },
    { word: "swing", sentence: "We played on the ___ at the park." },
    { word: "strong", sentence: "The rope was thick and ___." },
    { word: "wing", sentence: "The bird flapped its ___." },
  ]},

  // ===================================================================
  // Year 1 — r-controlled vowels, more split digraphs, extra vowel teams
  // ===================================================================
  ir: { label: "ir (bird)", grapheme: "ir", exampleWord: "bird", words: [
    { word: "bird", sentence: "A ___ landed on the fence." },
    { word: "girl", sentence: "The ___ rode her bike to school." },
    { word: "shirt", sentence: "I spilled juice on my ___." },
    { word: "first", sentence: "I was ___ in the race." },
    { word: "third", sentence: "She came in ___ place." },
    { word: "dirt", sentence: "The children played in the ___." },
    { word: "stir", sentence: "Please ___ the soup." },
    { word: "twirl", sentence: "The dancer began to ___." },
  ]},
  ur: { label: "ur (fur)", grapheme: "ur", exampleWord: "fur", words: [
    { word: "fur", sentence: "The cat has soft ___." },
    { word: "hurt", sentence: "I did not mean to ___ you." },
    { word: "curl", sentence: "Her hair has a natural ___." },
    { word: "burn", sentence: "Be careful not to ___ the toast." },
    { word: "turn", sentence: "It is your ___ to play." },
    { word: "nurse", sentence: "The ___ checked my temperature." },
    { word: "purse", sentence: "Mum kept her money in her ___." },
    { word: "church", sentence: "We visited the old ___." },
  ]},
  er: { label: "er (her)", grapheme: "er", exampleWord: "her", words: [
    { word: "her", sentence: "I gave the book to ___." },
    { word: "fern", sentence: "A green ___ grew by the path." },
    { word: "term", sentence: "This ___ we are learning fractions." },
    { word: "sister", sentence: "My ___ is older than me." },
    { word: "winter", sentence: "It snows here in ___." },
    { word: "under", sentence: "The cat hid ___ the bed." },
    { word: "ladder", sentence: "Dad climbed the ___ to fix the roof." },
    { word: "better", sentence: "I feel much ___ today." },
  ]},
  ore: { label: "ore (store)", grapheme: "ore", exampleWord: "store", words: [
    { word: "store", sentence: "We bought bread from the ___." },
    { word: "more", sentence: "Can I have some ___ juice?" },
    { word: "shore", sentence: "We walked along the ___." },
    { word: "score", sentence: "What was the final ___?" },
    { word: "snore", sentence: "My dad likes to ___ loudly." },
    { word: "chore", sentence: "Washing dishes is my least favourite ___." },
    { word: "before", sentence: "Wash your hands ___ dinner." },
    { word: "explore", sentence: "We went to ___ the forest." },
  ]},
  aw: { label: "aw (saw)", grapheme: "aw", exampleWord: "saw", words: [
    { word: "saw", sentence: "I ___ a rainbow after the rain." },
    { word: "paw", sentence: "The dog hurt its ___." },
    { word: "claw", sentence: "The cat scratched with its ___." },
    { word: "straw", sentence: "I drank my milkshake with a ___." },
    { word: "draw", sentence: "I like to ___ pictures of animals." },
    { word: "yawn", sentence: "I gave a big ___ before bed." },
    { word: "lawn", sentence: "Dad mowed the ___ this morning." },
    { word: "crawl", sentence: "The baby began to ___ across the floor." },
  ]},
  au: { label: "au (sauce)", grapheme: "au", exampleWord: "sauce", words: [
    { word: "sauce", sentence: "I put ___ on my pasta." },
    { word: "cause", sentence: "What was the ___ of the fire?" },
    { word: "haul", sentence: "We had to ___ the boxes upstairs." },
    { word: "launch", sentence: "We watched the rocket ___." },
    { word: "author", sentence: "The ___ signed my book." },
    { word: "astronaut", sentence: "The ___ floated in space." },
    { word: "dinosaur", sentence: "We saw a ___ skeleton at the museum." },
    { word: "fault", sentence: "It was not my ___." },
  ]},
  y_ee: { label: "_y (happy)", grapheme: "y", exampleWord: "happy", words: [
    { word: "happy", sentence: "I feel very ___ today." },
    { word: "funny", sentence: "That joke was really ___." },
    { word: "sunny", sentence: "It is a ___ day outside." },
    { word: "baby", sentence: "The ___ began to giggle." },
    { word: "party", sentence: "We are going to a birthday ___." },
    { word: "puppy", sentence: "Our new ___ loves to play." },
    { word: "story", sentence: "Grandpa told us a ___ before bed." },
    { word: "sleepy", sentence: "I feel ___ after a long day." },
  ]},
  ey: { label: "_ey (monkey)", grapheme: "ey", exampleWord: "monkey", words: [
    { word: "monkey", sentence: "The ___ swung from tree to tree." },
    { word: "donkey", sentence: "The ___ carried heavy bags up the hill." },
    { word: "chimney", sentence: "Smoke rose from the ___." },
    { word: "valley", sentence: "The village sat in a green ___." },
    { word: "honey", sentence: "Bees make ___ in their hive." },
    { word: "money", sentence: "I saved my ___ in a jar." },
    { word: "hockey", sentence: "We played ___ after school." },
    { word: "jockey", sentence: "The ___ rode the racehorse." },
  ]},
  eer: { label: "eer (deer)", grapheme: "eer", exampleWord: "deer", words: [
    { word: "deer", sentence: "A ___ ran across the road." },
    { word: "cheer", sentence: "The crowd began to ___ loudly." },
    { word: "steer", sentence: "Dad let me ___ the boat." },
    { word: "engineer", sentence: "The ___ fixed the bridge." },
    { word: "volunteer", sentence: "I will ___ to help clean the park." },
    { word: "career", sentence: "She wants a ___ in medicine." },
    { word: "reindeer", sentence: "A ___ pulled the sleigh." },
    { word: "cheerful", sentence: "My teacher always seems ___." },
  ]},
  ear_bear: { label: "ear (bear)", grapheme: "ear", exampleWord: "bear", words: [
    { word: "bear", sentence: "We saw a ___ at the zoo." },
    { word: "wear", sentence: "What will you ___ to the party?" },
    { word: "pear", sentence: "I ate a juicy ___." },
    { word: "swear", sentence: "I ___ that I locked the door." },
    { word: "underwear", sentence: "Please pack clean ___ for camp." },
  ]},
  are: { label: "are (care)", grapheme: "are", exampleWord: "care", words: [
    { word: "care", sentence: "Please take ___ crossing the road." },
    { word: "share", sentence: "Can we ___ the last slice?" },
    { word: "scare", sentence: "The loud noise gave me a ___." },
    { word: "stare", sentence: "It is rude to ___ at people." },
    { word: "square", sentence: "The box is a perfect ___." },
    { word: "spare", sentence: "Do you have a ___ pencil?" },
    { word: "compare", sentence: "Let's ___ our answers." },
    { word: "prepare", sentence: "We must ___ for the test." },
  ]},
  soft_c: { label: "soft c (city)", grapheme: "c", exampleWord: "city", words: [
    { word: "city", sentence: "We visited a big ___." },
    { word: "circle", sentence: "Draw a ___ on your page." },
    { word: "cent", sentence: "The lolly cost one ___." },
    { word: "cell", sentence: "Every living thing is made of a ___." },
    { word: "race", sentence: "I won the running ___." },
    { word: "ice", sentence: "The lake froze into ___." },
    { word: "dance", sentence: "We learned a new ___." },
    { word: "pencil", sentence: "I sharpened my ___." },
  ]},
  soft_g: { label: "soft g (giant)", grapheme: "g", exampleWord: "giant", words: [
    { word: "giant", sentence: "The story was about a friendly ___." },
    { word: "gem", sentence: "She found a shiny ___." },
    { word: "cage", sentence: "The bird lived in a ___." },
    { word: "page", sentence: "Turn to the next ___." },
    { word: "huge", sentence: "The elephant is a ___ animal." },
    { word: "orange", sentence: "I peeled an ___ for lunch." },
    { word: "gym", sentence: "We do sport in the ___." },
    { word: "giraffe", sentence: "The ___ has a very long neck." },
  ]},
  dge: { label: "dge (bridge)", grapheme: "dge", exampleWord: "bridge", words: [
    { word: "bridge", sentence: "We walked across the ___." },
    { word: "fridge", sentence: "Please put the milk in the ___." },
    { word: "judge", sentence: "The ___ decided who won." },
    { word: "badge", sentence: "I earned a scout ___." },
    { word: "edge", sentence: "Don't stand near the ___ of the cliff." },
    { word: "ledge", sentence: "The plant sat on the window ___." },
    { word: "dodge", sentence: "I had to ___ the puddle." },
    { word: "budge", sentence: "The heavy rock would not ___." },
  ]},
  tch: { label: "tch (catch)", grapheme: "tch", exampleWord: "catch", words: [
    { word: "catch", sentence: "Can you ___ the ball?" },
    { word: "watch", sentence: "I got a new ___ for my birthday." },
    { word: "witch", sentence: "The ___ wore a tall black hat." },
    { word: "match", sentence: "We watched the football ___." },
    { word: "kitchen", sentence: "Mum is cooking in the ___." },
    { word: "stretch", sentence: "Remember to ___ before you run." },
    { word: "sketch", sentence: "I drew a quick ___ of the tree." },
    { word: "ditch", sentence: "The car got stuck in a ___." },
  ]},

  // ===================================================================
  // Year 2 — extra correspondences, silent letters, consonant+le
  // ===================================================================
  ch_k: { label: "ch as /k/ (school)", grapheme: "ch", exampleWord: "school", words: [
    { word: "school", sentence: "I walk to ___ every morning." },
    { word: "echo", sentence: "My voice made an ___ in the cave." },
    { word: "chemist", sentence: "We picked up medicine from the ___." },
    { word: "chorus", sentence: "Everyone sang the ___ together." },
    { word: "stomach", sentence: "My ___ rumbled before lunch." },
    { word: "orchestra", sentence: "The ___ played a beautiful song." },
    { word: "chaos", sentence: "The classroom was full of ___ before the bell." },
    { word: "character", sentence: "My favourite book ___ is very brave." },
  ]},
  ph: { label: "ph (phone)", grapheme: "ph", exampleWord: "phone", words: [
    { word: "phone", sentence: "I called my mum on the ___." },
    { word: "dolphin", sentence: "We watched a ___ jump out of the water." },
    { word: "elephant", sentence: "The ___ sprayed water with its trunk." },
    { word: "photo", sentence: "Dad took a ___ of the sunset." },
    { word: "alphabet", sentence: "We learned the ___ song." },
    { word: "graph", sentence: "We drew a ___ of the results." },
    { word: "trophy", sentence: "Our team won the gold ___." },
    { word: "phrase", sentence: "Write a short ___ about your day." },
  ]},
  kn: { label: "kn silent k (knee)", grapheme: "kn", exampleWord: "knee", words: [
    { word: "knee", sentence: "I scraped my ___ on the path." },
    { word: "knife", sentence: "Be careful with that sharp ___." },
    { word: "knock", sentence: "Please ___ before you enter." },
    { word: "know", sentence: "Do you ___ the answer?" },
    { word: "knight", sentence: "The ___ rode a white horse." },
    { word: "knot", sentence: "I tied a ___ in the rope." },
    { word: "knit", sentence: "Grandma taught me how to ___." },
    { word: "knuckle", sentence: "I hurt my ___ on the door." },
  ]},
  wr: { label: "wr silent w (write)", grapheme: "wr", exampleWord: "write", words: [
    { word: "write", sentence: "Please ___ your name at the top." },
    { word: "wrist", sentence: "I hurt my ___ falling off my bike." },
    { word: "wrap", sentence: "Help me ___ this present." },
    { word: "wrong", sentence: "I got one answer ___." },
    { word: "wreck", sentence: "The ship became a ___ on the rocks." },
    { word: "wrench", sentence: "Dad used a ___ to fix the pipe." },
    { word: "wrinkle", sentence: "The shirt had one small ___." },
    { word: "wreath", sentence: "We hung a ___ on the door." },
  ]},
  mb: { label: "mb silent b (comb)", grapheme: "mb", exampleWord: "comb", words: [
    { word: "comb", sentence: "I used a ___ to fix my hair." },
    { word: "lamb", sentence: "The ___ followed its mother." },
    { word: "thumb", sentence: "I hurt my ___ closing the door." },
    { word: "climb", sentence: "We watched them ___ the tall ladder." },
    { word: "crumb", sentence: "There was one ___ left on the plate." },
    { word: "limb", sentence: "A big ___ fell from the tree." },
    { word: "numb", sentence: "My fingers felt ___ from the cold." },
    { word: "bomb", sentence: "The word ___ has a silent b." },
  ]},
  cle: { label: "consonant + le (candle)", grapheme: "le", exampleWord: "candle", words: [
    { word: "candle", sentence: "We lit a ___ on the cake." },
    { word: "bubble", sentence: "I blew a giant soap ___." },
    { word: "table", sentence: "Please set the ___ for dinner." },
    { word: "apple", sentence: "I packed an ___ for lunch." },
    { word: "little", sentence: "The puppy is very ___." },
    { word: "purple", sentence: "My favourite colour is ___." },
    { word: "simple", sentence: "The maths question was quite ___." },
    { word: "uncle", sentence: "My ___ came to visit for the weekend." },
  ]},
};

// Simple, common words that do NOT contain any of the patterns above.
// Used as "trick word" distractors for discrimination/sorting activities.
// The app filters out any that accidentally contain the chosen pattern.
const DISTRACTORS = [
  "cat", "dog", "sun", "hat", "pen", "big", "run", "jump", "sit", "top",
  "red", "box", "six", "mum", "dad", "bed", "leg", "pig", "hot", "wet",
  "bag", "cup", "log", "van", "zip", "fox", "hen", "web", "jet", "kid",
  "mud", "net", "lip", "mop", "bun", "fan", "gum", "hop", "jam", "lid",
  "rat", "map", "wig", "yes", "zoo", "elf", "ink", "oak", "urn", "art",
  "eat", "ice", "owl", "any", "ear", "eel", "add", "old", "cot", "dig",
  "fun", "hut", "job", "kit", "lit", "nap", "pit", "rob", "sob", "tug",
  "vet", "win", "yak", "gap", "hem", "ivy", "opt",
];
